apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  labels:
    app: kubedooms
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kubedooms
  template:
    metadata:
      labels:
        app: kubedooms
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - name: kubedoom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900
          protocol: TCP