apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgs
  name: delpoy
  namespace: pgs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: pgs
  template:
    metadata:
      labels:
        app: pgs
    spec:
      hostNetwork: true
      serviceAccountName: pgs
      containers:
      - image: postgres:10.13
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: testdatabase
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: POSTGRES_PASSWORD
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc
